name: System Telemetry Daemon

on:
  schedule:
    - cron: '0 1,13 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: sync-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  syslog:
    name: Core Driver Sync
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Initialize
        run: echo "🔧 Starter aktif. Menyiapkan rangkaian kolektor..."

      - name: Notify Boot
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TG_TOKEN/sendMessage \
            -d chat_id=$TG_CHAT_ID \
            --data-urlencode text="🟢 *Starter aktif.* Akan meneruskan ke kolektor berikutnya..." \
            -d parse_mode=Markdown

      - name: Small Jitter
        run: sleep $((RANDOM % 120 + 30))

      - name: Trigger Next (I/O Analyzer)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          curl -s -X POST -H "Authorization: Bearer $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/io-analyzer.yml/dispatches \
               -d '{"ref":"main"}'
